name: Deploy

on:
  push:
    branches: [dev, stable]

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Download and install tModLoader
        run: |
          curl -s -L https://github.com/tModLoader/tModLoader/releases/latest/download/tModLoader.zip -o tModLoader.zip
          unzip -q -o tModLoader.zip -d ../tModLoader
          rm tModLoader.zip

      - name: Create tModLoader.targets file
        shell: bash
        run: |
          cat >> ../tModLoader.targets << EOF
          <Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
            <Import Project="tModLoader\tMLMod.targets" />
          </Project>
          EOF

      - name: Build solution
        run: dotnet build Aurora.sln --configuration Release

      - name: List all
        shell: bash
        run: ls -R
        
      - name: Deploy .tmod artifact
        uses: actions/upload-artifact@v3
        with:
          name: Aurora.tmod
          path: ./bin/Saves/tModLoader/Mods/Aurora.tmod

      - name: Deploy .dll artifact
        uses: actions/upload-artifact@v3
        with:
          name: Aurora.dll
          path: ./bin/Release/net6.0/Aurora.dll

      - name: Deploy action across Discord
        uses: sarisia/actions-status-discord@v1  
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_DEPLOY }}
          title: New version of `Aurora` is ready!
          description: |
            Click [here](https://github.com/shnakamura/Aurora/actions/runs/${{ github.run_id }}) to view.