name: Linter

on:
  push:
    branches: [ "stable", "dev" ]
  pull_request:
    branches: [ "stable", "dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore .NET dependencies
      run: dotnet restore
      
    - name: Setup tModLoader targets
      run: |
        mkdir -p ../tMod
        echo '<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
            <Import Project="../tMod/tMLMod.targets" />
        </Project>' > ../tModLoader.targets
        
        cd ../tMod
        wget https://github.com/tModLoader/tModLoader/releases/latest/download/tModLoader.zip
        unzip tModLoader.zip
        
    - name: Lint
      run: dotnet format --verify-no-changes --config .editorconfig Aurora.sln